version: '3.8'

services:
  backend:
    build: 
      context: ./backend
    ports:
      - "5257:5257"  # your backend port
    working_dir: /app
    volumes:
      - ./backend:/app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  frontend:
    build: 
      context: ./frontend
    ports:
      - "3000:3000"  # your React port
    working_dir: /app
    volumes:
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
